### ISSUE TITLE
Potential bug in Dialog

### ISSUE THREAD

**Issue by Noxsios** [defenseunicorns/UnicornUI#101]
Still seeing the unintended behavior of Dialog not removing its change to `document.body.style.overflow` from #78 , I believe the below line is the culprit.

https://github.com/defenseunicorns/UnicornUI/blob/a5ad96b237afcdc0fa4a717af199b2a38f853249/uui/src/lib/Dialog/Dialog.svelte#L23

**Comment by mike-winberry** [comment]
Yeah that is in fact the culprit lol. I’ll be fixing now. Should be releasing this afternoon or evening.
