### ISSUE TITLE
Scoped Styles 

### ISSUE THREAD

**Issue by mike-winberry** [defenseunicorns/UnicornUI#114]
### Box component
- [x] add scopedStylesProp that accepts js object
  - [x] generate a uuid. 
  - [x]  generate the css if prop exists
     - consider appending to head and removing on destroy. (using the uuid)
- [x] support for media queries. 

- [ ] Usability test for flow and target placeholder (see note below for options)
- [ ] Create a blog post of decisions and feature (why Svelte sucks at this)

**Comment by Madeline-UX** [comment]
HMW enable one off-variant changes to a component without impacting global styles

Examples: MUI uses emotion

Need: Option to add scoped styles to a single component instance without using or changing global styles. 

UX Questions: 
What should scoped styles target placeholder be? 
- $self (python)
- $this (java)

Svelte uses $$ a lot (ex. $props)

UX to Do: 

- [ ] test flow with users @Madeline-UX

**Comment by mike-winberry** [comment]
![Screenshot 2023-02-07 at 11 18 16 AM](https://user-images.githubusercontent.com/86802655/217343694-6f2fd4fb-fb9e-4ef3-8963-82eb4827ff46.png)
