### ISSUE TITLE
Add SSX to components

### ISSUE THREAD

**Issue by mike-winberry** [defenseunicorns/UnicornUI#140]
SSX should be applied to the top level of all components to allow scopedStyling.

**Comment by mike-winberry** [comment]
- [ ] Box
- [ ] Button
- [ ] IconButton
- [ ] Accordion 
- [ ] Stepper
- [ ] Dialog
- [ ] Typography
- [ ] Chip
- [ ] TextField

**Comment by Madeline-UX** [comment]
References for Elevation design from material

https://m2.material.io/design/color/dark-theme.html#properties

https://mui.com/material-ui/react-paper/#elevation

https://www.figma.com/file/FVxDm72mPiUTKmAD44ixmX/MUI-Components?node-id=6754%3A50525&t=2iSkbGhBQFof39G5-1

**Comment by mike-winberry** [comment]
https://m2.material.io/design/environment/elevation.html#default-elevations 
### Paper/Elevation should be added to 
- [ ] Accordion
- [ ] List
- [ ] Dialog (ensure its correct)
- [ ] Chip?.

**Comment by mike-winberry** [comment]
Closing in favor of smaller stories.
