### ISSUE TITLE
Elevation

### ISSUE THREAD

**Issue by mike-winberry** [defenseunicorns/UnicornUI#142]
References for Elevation design from material

https://m2.material.io/design/color/dark-theme.html#properties

https://mui.com/material-ui/react-paper/#elevation

https://www.figma.com/file/FVxDm72mPiUTKmAD44ixmX/MUI-Components?node-id=6754%3A50525&t=2iSkbGhBQFof39G5-1

- [ ] Create a reusable and succinct way of applying elevation. 
- [ ] Create paper component. 
  - [ ]  will need input on coloring etc.

**Comment by TristanHoladay** [comment]
https://github.com/material-components/material-components-web/tree/master/packages/mdc-elevation

**Comment by TristanHoladay** [comment]
Looking at https://m2.material.io/design/color/dark-theme.html#properties elevation to overlay opacity percentage mappings it's unclear to me how they're deciding to match moves in elevation to jumps in overlay opacity. There does not seem to be a discernible pattern. Are we going to just create our own mapping based on this one?

Currently, paper opacity is determined from direct conversion of elevation to percentage (i.e. 10 = .10, 24 = .24).
