### ISSUE TITLE
Update Unicorn UI Dark theme

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/UnicornUI#157]
Update the background and surface color to these

<img width="531" alt="Screenshot 2023-03-17 at 1 50 43 PM" src="https://user-images.githubusercontent.com/92826525/225993043-834ea97c-a1fa-4022-8036-7d06ba163462.png">

**Comment by mike-winberry** [comment]
## Dark Theme (default-palettes)
- [x] update surface color
- [x] update background color.
