### ISSUE TITLE
[Bug] Paper Overlay Should Not Scroll

### ISSUE THREAD

**Issue by TristanHoladay** [defenseunicorns/UnicornUI#167]
When making Paper a scrollable container, the overlay scrolls as well meaning that not all content has an overlay covering it.

**Screenshots**
<img width="1273" alt="Screenshot 2023-03-27 at 12 27 07 PM" src="https://user-images.githubusercontent.com/40547442/228033067-ec38f764-5d88-415d-917d-905d36cc4e2b.png">

**Desktop (please complete the following information):**
 - Browser [chrome, brave]
 - UnicornUI Version [v0.0.39]

**Comment by mike-winberry** [comment]
@TristanHoladay This will fix the other issues you are having with the Overlay. May have repercussions for #153 #96
