### ISSUE TITLE
Fix accordion background colors. 

### ISSUE THREAD

**Issue by mike-winberry** [defenseunicorns/UnicornUI#28]
# Fixes accordion different background color for sub components bug
- [x] .accordion uses theme surface as background color by default sub components inherit. 
- [x] .accordion uses the theme-on-surface as text color by default sub components inherit. 
- [x] Add to documentation that the theme-surface variable controls the backgrounds.

**Comment by imanpalsingh** [comment]
Hey, your netlify app isn't working, wanted to check this component
