### ISSUE TITLE
Add Text Field Component

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/UnicornUI#61]
https://material-components.github.io/material-components-web-catalog/#/component/text-field

**Comment by TristanHoladay** [comment]
## variants
- [ ] outlined
- - [ ] standard
- - [ ] shaped
- - [ ] helper text
- - [ ] character counter
- - [ ] validation
- [ ] filled 
- - [ ] standard
- - [ ] shaped
- - [ ] helper text
- - [ ] character counter
- - [ ] validation

Possible props for further iterations: 
InputProps?
size? sm | md | lg | xl
