### ISSUE TITLE
Stepper Horizontal's text is not aligned to the middle

### ISSUE THREAD

**Issue by Noxsios** [defenseunicorns/UnicornUI#75]
Per the Figma spec the Stepper Horizontal's step text should be aligned to the center along the Y axis:

<img width="554" alt="Screenshot 2023-01-12 at 5 11 10 PM" src="https://user-images.githubusercontent.com/50058333/212192404-e56ef04e-88e3-4cc8-8624-6a5c0c31ced5.png">

Currently:

<img width="957" alt="Screenshot 2023-01-12 at 5 15 47 PM" src="https://user-images.githubusercontent.com/50058333/212192879-290ecd56-218e-4e1f-8548-18ad48429fd4.png">

**Comment by TristanHoladay** [comment]
Fix for horizontal stepper causes side-effect bug for divider placement in vertical stepper. Looking into a fix for that as well before pushing.
