### ISSUE TITLE
Tweak Stepper component

### ISSUE THREAD

**Issue by Noxsios** [defenseunicorns/UnicornUI#99]
The stepper component contains some default CSS that adds some unnecessary padding.

Adding `padding-inline: 0` to the `ol` element fixed the initial spacing.

before:

<img width="788" alt="Screenshot 2023-01-24 at 12 23 01 PM" src="https://user-images.githubusercontent.com/50058333/214376288-933a0554-60f7-4f7a-bb6c-41981981dd93.png">

after:

<img width="782" alt="Screenshot 2023-01-24 at 12 23 44 PM" src="https://user-images.githubusercontent.com/50058333/214376425-1149980c-85f0-4d83-bc8b-48ef89562ee5.png">

additionally, the stepper does not properly center due to the final element still containing `flex-grow: 1`, setting the last item of the stepper to have `flex-grow: 0` fixes this.

before:

<img width="782" alt="Screenshot 2023-01-24 at 12 23 44 PM" src="https://user-images.githubusercontent.com/50058333/214376425-1149980c-85f0-4d83-bc8b-48ef89562ee5.png">

after:

<img width="785" alt="Screenshot 2023-01-24 at 12 25 42 PM" src="https://user-images.githubusercontent.com/50058333/214376852-5cb1eaea-f487-42b9-bb0e-6ce07f360999.png">

**Comment by Noxsios** [comment]
Example code:

```html
<div class="stepper-container">
  <Stepper ... />
</div>

<style>
	.stepper-container {
		max-width: 600px;
		margin: 0 auto;
		width: 100%;
	}
	/* remove when UnicornUI updates w/ fix */
	:global(.stepper-container ol) {
		padding-inline: 0;
	}
	:global(.stepper-container li:last-child) {
		flex-grow: 0;
	}
</style>
```

result:

<img width="788" alt="Screenshot 2023-01-24 at 12 40 03 PM" src="https://user-images.githubusercontent.com/50058333/214380060-6604da8e-e163-4ba7-98f8-cd358f9a1520.png">

**Comment by TristanHoladay** [comment]
Thanks for catching this and giving the tweaks!
